nx: 9
ny: 6
image_folder: "test_images/project2/camera_cal"
output_folder: "test_images/project2/cal_out"
calibration_files: [
  "calibration1.jpg",
  "calibration2.jpg",
  "calibration3.jpg",
  "calibration4.jpg",
  "calibration5.jpg",
  "calibration6.jpg",
  "calibration7.jpg",
  "calibration8.jpg",
  "calibration9.jpg",
  "calibration10.jpg",
  "calibration11.jpg",
  "calibration12.jpg",
  "calibration13.jpg",
  "calibration14.jpg",
  "calibration15.jpg",
  "calibration16.jpg",
  "calibration17.jpg",
  "calibration18.jpg",
  "calibration19.jpg",
  "calibration20.jpg"]
